language: python
cache: pip
notifications:
  email: false
python:
  - "2.7"
  - "3.4"
  - "3.6"
os:
  - linux
# command to install dependencies
addons:
  apt:
    packages:
      - libopenblas-dev
      - liblapack-dev
      - libxc-dev
install:
  - pip install ase
  - pip install --no-binary gpaw gpaw
  - pip install pymatgen
  - pip install .
# command to run tests
script:
  - xvfb-run python setup.py test
