language: python
cache: pip
notifications:
  email: false
python:
  - "3.4"
  - "3.6"
os:
  - linux
# command to install dependencies
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libxc-dev
install:
  - pip install coverage python-coveralls
  - pip install ase==3.15.0
  - pip install --no-binary gpaw gpaw==1.3.0
  - gpaw install-data --register gpaw_setups
  - pip install pymatgen
  - pip install .
# command to run tests
script:
  - xvfb-run coverage run --source galore setup.py test
after_success:
  - coveralls
